
version: '2'
services:
  web:
    build: .
    ports:
        - "8888:8888"
    links:
      - db:mysql
    container_name: counterapp_web_1
    depends_on:
      - db
  db:
    image: mysql/mysql-server:5.7
    restart: always
    container_name: counterapp_db_1
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_ROOT_HOST: "%"
