version: '3.3'
services:
  web:
    build: .
    restart: always
    ports:
        - "8888:8888"
    links:
      - db:mysql
    container_name: ai_web
    depends_on:
      - db
  db:
    image: mysql:5.7.22
    command:
      - --default_authentication_plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    container_name: ai_db
    environment:
      MYSQL_USER: "ali"
      MYSQL_DATABASE: text_process
      MYSQL_PASSWORD: "aliali"
      MYSQL_ROOT_PASSWORD: "aliali"
      MYSQL_ROOT_HOST: "%"

volumes:
    db_data: